; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
lib_deps = enjoyneering/AHT10@^1.1.0

;upload_protocol = espota
;upload_port = myesp8266.local
;upload_port = 192.168.4.101
; each flag in a new line
;upload_flags =
;  --port=8266